// <auto-generated />
using System;
using BoutiqueShoes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoutiqueShoes.Migrations
{
    [DbContext(typeof(BoutiqueShoesContext))]
    [Migration("20240424190742_BoutiqueMigration")]
    partial class BoutiqueMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BoutiqueShoes.Models.Commande", b =>
                {
                    b.Property<int>("CommandeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommandeId"), 1L, 1);

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime2");

                    b.HasKey("CommandeId");

                    b.ToTable("Commande");
                });

            modelBuilder.Entity("BoutiqueShoes.Models.CommandeShoes", b =>
                {
                    b.Property<int>("CommandeShoesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommandeShoesId"), 1L, 1);

                    b.Property<int>("CommandeId")
                        .HasColumnType("int");

                    b.Property<int>("QuantiteCommande")
                        .HasColumnType("int");

                    b.Property<int>("ShoesId")
                        .HasColumnType("int");

                    b.HasKey("CommandeShoesId");

                    b.ToTable("CommandeShoes");
                });

            modelBuilder.Entity("BoutiqueShoes.Models.Details", b =>
                {
                    b.Property<int>("DetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailsId"), 1L, 1);

                    b.Property<string>("CouleurChaussure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionChaussure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarqueChaussure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TailleChaussure")
                        .HasColumnType("int");

                    b.HasKey("DetailsId");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("BoutiqueShoes.Models.Inventaire", b =>
                {
                    b.Property<int>("InventaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventaireId"), 1L, 1);

                    b.Property<int>("NombreEnStocke")
                        .HasColumnType("int");

                    b.HasKey("InventaireId");

                    b.ToTable("Inventaire");
                });

            modelBuilder.Entity("BoutiqueShoes.Models.Shoes", b =>
                {
                    b.Property<int>("ShoesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoesId"), 1L, 1);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("DetailsId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("InventaireId")
                        .HasColumnType("int");

                    b.Property<string>("ShoesName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ShoesPrice")
                        .HasColumnType("float");

                    b.HasKey("ShoesId");

                    b.ToTable("Shoes");
                });
#pragma warning restore 612, 618
        }
    }
}
